name: 喜马拉雅极速版

on:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requirements'
        run: pip install -r ./workflow/requirements.txt

      - name: 'run 喜马拉雅极速版'
        run: python3 ./workflow/xmly_speed.py
        env:
          TZ: Asia/shanghai
          XMLY_SPEED_COOKIE: ${{ github.event.client_payload.XMLY_SPEED_COOKIE || secrets.XMLY_SPEED_COOKIE }}
          XMLY_ACCUMULATE_TIME: ${{ github.event.client_payload.XMLY_ACCUMULATE_TIME || secrets.XMLY_ACCUMULATE_TIME }}
          XMLY_ACCUMULATE_INDEX: ${{ github.event.client_payload.XMLY_ACCUMULATE_INDEX || secrets.XMLY_ACCUMULATE_INDEX }}
          XMLY_ACCUMULATE_HOURS: ${{ github.event.client_payload.XMLY_ACCUMULATE_HOURS || secrets.XMLY_ACCUMULATE_HOURS }}
          XMLY_ANDROID_AGENT: ${{ github.event.client_payload.XMLY_ANDROID_AGENT || secrets.XMLY_ANDROID_AGENT }}
          BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
          SYNCURL: https://github.com/Zero-S1/xmly_speed/raw/master/xmly_speed.py