
name: 闪挣

on:
  workflow_dispatch:
  schedule:
     - cron: '*/10 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
      steps:
     
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/TaskActions
      - name: '运行 【闪挣】'
        run: |
          cd ~/TaskActions
          node sz.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          SZURL: ${{ secrets.SZURL }}
          SZHD: ${{ secrets.SZHD }}
          
          
